### ISSUE TITLE
Website is too hot

### ISSUE THREAD

**Issue by Riathoir** [jreverett/jamieeverett.co.uk#4]
Hello,
I would like to raise a complaint that every-time I visit your website I seem to catch fire. 
Your graphics are just too hot for the internet, could you possibly dial down the spice?

Thank you for your help.

**Comment by jreverett** [comment]
Thanks for the feedback, I've made some minor changes but I'm worried that the website is now spicier than ever

Thoughts?


<img width="962" alt="Screenshot 2021-03-30 at 19 50 46" src="https://user-images.githubusercontent.com/36159269/113040875-3a570900-9191-11eb-94e6-c97fcf48c980.png">
